from pm4py.objects.log.obj import EventLog,Trace,Event
from pm4py.objects.log.exporter.xes import exporter

from datetime import datetime, timedelta
import random
import numpy as np


#Configurables

IMPORT_PATH = ""
EXPORT_PATH = "./logandother/random letters"

NO_COMPLIANT_TRACES = 420
NO_DEVIATING_TRACES = 80

START_DATE = datetime(2023, 1, 1)
RANGE_OF_DAYS = 102
MINUTE_MINIMUM = 5
MINUTE_MAXIMUM = 20







# Function to generate a random timestamp within a range
def generate_random_timestamp():
    random_days = random.randint(0, RANGE_OF_DAYS)  # random days up to 10                                    
    random_seconds = random.randint(0, 86400)  # random seconds in a day                            
    return START_DATE + timedelta(days=random_days, seconds=random_seconds)

# Function to generate a trace from a given string
def generate_trace(variant,organisation):
    trace = Trace()
    current_time = generate_random_timestamp()
    for activity in variant:
        event = Event({
            "concept:name": activity,
            "org:resource": organisation,
            "time:timestamp": current_time
            })
        trace.append(event)
        current_time += timedelta(minutes=random.randint(MINUTE_MINIMUM, MINUTE_MAXIMUM))  # Increment time between events 
    log.append(trace)

# Function to generate deviant/compliant traces for one organisation
def generating_traces(variant,organization,no_traces):
    #create a random pareto distribution with 
    pareto = np.random.pareto(a=3, size=variants[i].__len__())
    pareto = np.floor(pareto/np.min(pareto)).astype(int)
    pareto = (pareto/np.sum(pareto)*no_traces).astype(int)
    for variant_index in range(pareto.__len__()): 
        for _ in range(pareto[variant_index]):
            generate_trace(variant[variant_index],organization)



# Names of the organisations
organizations = ["Phone","SoC Factory","Silicon Mining","Screen Factory","Battery Factory"]

# Define complaint trace variants(can be generated by AI but need to be checked whether they are compliant or not)
variants = [
    [
        ["B","G","L","W","X","Y","K"],
        ["B","G","W","X","L","Y","K"],
        ["B","G","W","L","X","Y","K"],
        ["B","G","X","W","L","Y","K"],
        ["B","G","Y","X","L","W","K"],
        ["B","G","W","Y","X","L","K"],
        ["B","G","W","L","Y","X","K"],
        ["A","D","C","F","N","Y","E","M"],
        ["A","D","C","Y","F","N","E","M"],
        ["A","D","Y","C","F","E","N","M"],
        ["A","D","F","Y","C","N","E","M"],
        ["A","D","F","C","N","E","Y","M"],
    ],
    [
        ["Store Screen", "Apply Screen to Frame", "Store Battery", "Apply Battery to Frame", "Store SoC", "Apply SoC to Frame", "Package Phone", "Ship Phone"],
        ["Store Battery", "Apply Battery to Frame", "Store Screen", "Apply Screen to Frame", "Store SoC", "Apply SoC to Frame", "Package Phone", "Ship Phone"],
        ["Store SoC", "Apply SoC to Frame", "Store Battery", "Apply Battery to Frame", "Store Screen", "Apply Screen to Frame", "Package Phone", "Ship Phone"],
        ["Store Screen", "Apply Screen to Frame", "Store SoC", "Apply SoC to Frame", "Store Battery", "Apply Battery to Frame", "Package Phone", "Ship Phone"],
        ["Store Screen", "Store Battery", "Store SoC", "Apply SoC to Frame", "Apply Battery to Frame", "Apply Screen to Frame", "Package Phone", "Ship Phone"],
        ["Store Battery", "Store Screen", "Store SoC", "Apply SoC to Frame", "Apply Screen to Frame", "Apply Battery to Frame", "Package Phone", "Ship Phone"],
        ["Store Battery", "Store SoC", "Store Screen", "Apply Screen to Frame", "Apply SoC to Frame", "Apply Battery to Frame", "Package Phone", "Ship Phone"],
        ["Store SoC", "Store Screen", "Store Battery", "Apply Battery to Frame", "Apply Screen to Frame", "Apply SoC to Frame", "Package Phone", "Ship Phone"],
        ["Store SoC", "Store Battery", "Store Screen", "Apply Screen to Frame", "Apply Battery to Frame", "Apply SoC to Frame", "Package Phone", "Ship Phone"],
        ["Store Battery", "Store SoC", "Apply SoC to Frame", "Store Screen", "Apply Screen to Frame", "Apply Battery to Frame", "Package Phone", "Ship Phone"],
        ["Store Battery", "Store SoC", "Apply SoC to Frame", "Apply Battery to Frame", "Store Screen", "Apply Screen to Frame", "Package Phone", "Ship Phone"],
        ["Store Screen", "Store SoC", "Apply SoC to Frame", "Apply Screen to Frame", "Store Battery", "Apply Battery to Frame", "Package Phone", "Ship Phone"],
    ],
    [
        ['Ship Silicon to Factory', 'Create Weaver', 'Test Weaver', 'Apply Lithography', 'Ship to Phone factory'],
        ['Ship Silicon to Factory', 'Create Weaver', 'Test Weaver', 'Recycle', 'Create Weaver', 'Test Weaver', 'Apply Lithography', 'Ship to Phone factory'],
        ['Ship Silicon to Factory', 'Create Weaver', 'Test Weaver', 'Recycle', 'Create Weaver', 'Test Weaver', 'Recycle', 'Create Weaver', 'Test Weaver', 'Apply Lithography', 'Ship to Phone factory'],
        ['Ship Silicon to Factory', 'Create Weaver', 'Test Weaver', 'Recycle', 'Create Weaver', 'Test Weaver', 'Recycle', 'Create Weaver', 'Test Weaver', 'Recycle', 'Create Weaver', 'Test Weaver', 'Apply Lithography', 'Ship to Phone factory'],
    ],
    [
        ['Mine Silicon','Move to Central Storage','Ship to Customer'],
        ['Mine Silicon','Disposal of impure Silicon'],
    ],
    [
        ["Create Backlight", "Apply Backlight to Frame", "Create LCD-Layer", "Apply LCD-Layer to Frame", "Create Polarization Filter", "Apply Polarization Filter", "Ship Screen"],
        ["Create LCD-Layer", "Create Backlight", "Apply Backlight to Frame", "Apply LCD-Layer to Frame", "Create Polarization Filter", "Apply Polarization Filter", "Ship Screen"],
        ["Create Polarization Filter", "Create Backlight", "Apply Backlight to Frame", "Create LCD-Layer", "Apply LCD-Layer to Frame", "Apply Polarization Filter", "Ship Screen"],
        ["Create LCD-Layer", "Create Polarization Filter", "Create Backlight", "Apply Backlight to Frame", "Apply LCD-Layer to Frame", "Apply Polarization Filter", "Ship Screen"],
        ["Create Backlight", "Apply Backlight to Frame", "Create Polarization Filter", "Create LCD-Layer", "Apply LCD-Layer to Frame", "Apply Polarization Filter", "Ship Screen"],
    ],
    [
        ["Create Anode", "Create Separator", "Combine Anode with Separator", "Create Cathode", "Combine Cathode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Cathode", "Create Separator", "Create Anode", "Combine Anode with Separator", "Combine Cathode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Separator", "Create Anode", "Combine Anode with Separator", "Create Cathode", "Combine Cathode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Anode", "Create Cathode", "Create Separator", "Combine Anode with Separator", "Combine Cathode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Cathode", "Create Anode", "Create Separator", "Combine Anode with Separator", "Combine Cathode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Separator", "Create Cathode", "Create Anode", "Combine Anode with Separator", "Combine Cathode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Anode", "Create Separator", "Create Cathode", "Combine Cathode with Separator", "Combine Anode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Cathode", "Create Separator", "Create Anode", "Combine Cathode with Separator", "Combine Anode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Separator", "Create Anode", "Create Cathode", "Combine Cathode with Separator", "Combine Anode with Separator", "Close up Battery", "Ship Battery to phone factory"],
    ]
]

# Define deviant trace variants(can be generated by AI but need to be checked whether they are compliant or not)
non_conform_variants = [
    [
        ["A","D","N","E","C","F","M","Y"],
        ["A","F","N","E","C","D","M","Y"],
        ["A","D","N","E","W","F","X","K"],
        ["B","G","N","E","W","F","Y","K"],
    ],
    [
        ["Store Screen", "Store Battery", "Store SoC", "Apply Screen to Frame", "Apply Battery to Frame", "Ship Phone"],
        ["Store SoC", "Apply SoC to Frame", "Apply Screen to Frame", "Store Battery", "Package Phone", "Ship Phone"], 
        ["Store Battery", "Apply SoC to Frame", "Store Screen", "Apply Screen to Frame", "Store SoC", "Apply Battery to Frame", "Package Phone", "Ship Phone"],  
        ["Store Screen", "Store Battery", "Store SoC", "Apply Battery to Frame", "Apply Screen to Frame", "Apply SoC to Frame", "Package Phone"],  
    ],
    [
        ['Ship Silicon to Factory', 'Test Weaver', 'Apply Lithography', 'Ship to Phone factory'],
        ['Ship Silicon to Factory', 'Recycle', 'Test Weaver', 'Apply Lithography', 'Ship to Phone factory'],
        ['Create Weaver', 'Test Weaver', 'Apply Lithography', 'Ship to Phone factory'],
        ['Ship Silicon to Factory', 'Create Weaver', 'Apply Lithography', 'Ship to Phone factory'],
        ['Ship Silicon to Factory', 'Create Weaver', 'Test Weaver', 'Recycle', 'Apply Lithography']
    ],
    [
        ['Move to Central Storage','Mine Silicon','Ship to Customer'],
        ['Ship to Customer','Mine Silicon','Move to Central Storage'],
        ['Mine Silicon','Mine Silicon','Ship to Customer'],
        ['Mine Silicon','Ship to Customer','Mine Silicon','Move to Central Storage'],
    ],
    [
        ["Create LCD-Layer", "Apply LCD-Layer to Frame", "Ship Screen"],
        ["Create Backlight", "Apply Backlight to Frame", "Ship Screen"],
        ["Create Polarization Filter", "Apply Polarization Filter", "Ship Screen"],
        ["Apply LCD-Layer to Frame", "Create LCD-Layer", "Create Backlight", "Apply Backlight to Frame", "Ship Screen"],
        ["Apply Backlight to Frame", "Create Backlight", "Create LCD-Layer", "Apply LCD-Layer to Frame", "Create Polarization Filter", "Apply Polarization Filter"],
    ],
    [
        ["Create Separator", "Combine Anode with Separator", "Create Anode", "Create Cathode", "Combine Cathode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Cathode", "Combine Anode with Separator", "Create Separator", "Create Anode", "Combine Cathode with Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Combine Anode with Separator", "Create Anode", "Create Separator", "Combine Cathode with Separator", "Create Cathode", "Close up Battery", "Ship Battery to phone factory"],
        ["Create Anode", "Create Cathode", "Combine Anode with Separator", "Combine Cathode with Separator", "Create Separator", "Close up Battery", "Ship Battery to phone factory"],
        ["Combine Cathode with Separator", "Create Cathode", "Create Separator", "Combine Anode with Separator", "Create Anode", "Close up Battery", "Ship Battery to phone factory"],
    ]

]





# Create an empty event log
log = EventLog()

for i in range(variants.__len__()):
    i=0
    generating_traces(variants[i],organizations[i],NO_COMPLIANT_TRACES)
    generating_traces(non_conform_variants[i],organizations[i],NO_DEVIATING_TRACES)

# Export the log to an XES file at EXPORT_PATH
exporter.apply(log, EXPORT_PATH)


